# Generated by Django 4.0.4 on 2022-04-23 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_usuarios_options_alter_usuarios_apellido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ['nombre'], 'verbose_name': 'Usuarios', 'verbose_name_plural': 'Usuario(s)'},
        ),
        migrations.CreateModel(
            name='ruta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.CharField(max_length=200, verbose_name='Ruta')),
                ('usuario_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roles.usuarios')),
            ],
            options={
                'verbose_name': 'ruta',
                'verbose_name_plural': 'rutas',
                'ordering': ['ruta'],
            },
        ),
    ]
