# Generated by Django 4.0.4 on 2022-04-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_alter_usuarios_options_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creacion o modificación'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creacion o modificación'),
        ),
    ]
