# Generated by Django 4.0.4 on 2022-05-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vista', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios_dePrueva',
            new_name='Usuarios',
        ),
    ]
